import fs from 'fs';
import path from 'path';
import YAML from 'yaml';

// 警告ヘッダー
const WARNING_HEADER = `<!--
  GENERATED VIEW - DO NOT EDIT THIS FILE DIRECTLY.
  This file is generated from its corresponding YAML model.
  To change the content, edit the YAML file instead.
-->\n\n`;

export function renderDocument(model) {
  let md = `${WARNING_HEADER}`;
  md += `# ${model.title}\n\n`;
  
  md += `## Metadata\n\n`;
  md += `| Key | Value |\n`;
  md += `| --- | --- |\n`;
  md += `| ID | ${model.id} |\n`;
  md += `| Source | ${model.provenance.source} |\n`;
  md += `| Authored By | ${model.provenance.authored_by.role} (${model.provenance.authored_by.identifier}) |\n`;
  md += `| Authored At | ${model.provenance.authored_at} |\n\n`;
  
  md += `## Content\n\n`;
  md += `${model.content}\n`;
  
  return md;
}

export function renderRecord(model, registryState) {
  let md = `${WARNING_HEADER}`;
  md += `# [${model.id}] ${model.title}\n\n`;

  md += `## Metadata\n\n`;
  md += `| Key | Value |\n`;
  md += `| --- | --- |\n`;
  md += `| ID | ${model.id} |\n`;
  md += `| Type | ${model.type} |\n`;
  if (registryState) {
    md += `| State | ${registryState} |\n`;
  }
  md += `| Authored By | ${model.provenance.authored_by.role} (${model.provenance.authored_by.identifier}) |\n`;
  md += `| Authored At | ${model.provenance.authored_at} |\n\n`;
  
  md += `## Context\n\n`;
  md += `${model.context}\n\n`;

  if (model.decision) {
    md += `## Decision\n\n${model.decision}\n\n`;
  }

  if (model.rationale) {
    md += `## Rationale\n\n${model.rationale}\n\n`;
  }

  if (model.implications && model.implications.length > 0) {
    md += `## Implications\n\n`;
    model.implications.forEach(imp => {
      md += `- ${imp}\n`;
    });
    md += `\n`;
  }
  
  if (model.rejected_alternatives && model.rejected_alternatives.length > 0) {
    md += `## Rejected Alternatives\n\n`;
    model.rejected_alternatives.forEach(alt => {
      md += `### ${alt.name} (${alt.id})\n\n`;
      md += `${alt.reason}\n\n`;
    });
  }
  
  if (model.review_trigger && model.review_trigger.length > 0) {
    md += `## Review Triggers\n\n`;
    model.review_trigger.forEach(trig => {
      md += `- ${trig}\n`;
    });
    md += `\n`;
  }

  if (model.type === 'LearningRecord') {
    if (model.learning) {
      md += `## Learning\n\n${model.learning}\n\n`;
    }
    if (model.applicability) {
      md += `## Applicability\n\n${model.applicability}\n\n`;
    }
    if (model.source_change) {
      md += `**Source change**: ${model.source_change}\n\n`;
    }
  }

  return md;
}

export function renderModelFile(yamlFilePath, viewFilePath, registryState) {
  const fileContent = fs.readFileSync(yamlFilePath, 'utf8');
  const model = YAML.parse(fileContent);

  let mdContent = '';
  if (model.type && model.type.endsWith('Record')) {
    mdContent = renderRecord(model, registryState);
  } else {
    mdContent = renderDocument(model);
  }

  const mdFilePath = viewFilePath || yamlFilePath.replace(/\.yaml$/, '.md');
  fs.mkdirSync(path.dirname(mdFilePath), { recursive: true });
  fs.writeFileSync(mdFilePath, mdContent, 'utf8');
  console.log(`  [OK] ${mdFilePath}`);
}

export function renderIndexFiles(workspaceRoot) {
  const recordsRegPath = path.join(workspaceRoot, 'registry/records.yaml');
  if (!fs.existsSync(recordsRegPath)) {
    console.log(`Registry file not found: ${recordsRegPath}`);
    return;
  }
  
  const recordsRegistry = YAML.parse(fs.readFileSync(recordsRegPath, 'utf8'));
  const records = recordsRegistry.records || [];
  
  let md = `${WARNING_HEADER}`;
  md += `# Project Knowledge Records Index\n\n`;
  md += `| ID | Title | Type | State | Date | Author |\n`;
  md += `| --- | --- | --- | --- | --- | --- |\n`;
  
  for (const recordRef of records) {
    const yamlPath = path.join(workspaceRoot, recordRef.canonical);
    if (fs.existsSync(yamlPath)) {
      const model = YAML.parse(fs.readFileSync(yamlPath, 'utf8'));
      const authoredBy = model.provenance?.authored_by 
        ? `${model.provenance.authored_by.role} (${model.provenance.authored_by.identifier})`
        : 'Unknown';
      const authoredAt = model.provenance?.authored_at || 'Unknown';
      
      const viewPath = recordRef.views && recordRef.views[0] ? recordRef.views[0] : recordRef.canonical.replace(/\.yaml$/, '.md');
      const relLink = path.relative('views', viewPath);
      md += `| [${model.id}](${relLink}) | ${model.title} | ${model.type} | ${recordRef.state} | ${authoredAt} | ${authoredBy} |\n`;
    }
  }
  
  const outputPath = path.join(workspaceRoot, 'views/all-records.md');
  fs.writeFileSync(outputPath, md, 'utf8');
  console.log(`Generated Knowledge Records Index: ${outputPath}`);
}
